responses = {
    # Greeting Responses
   "hello": "Hello there! How can I assist you today?",
    "hi": "Hi there! How can I help you today?",
    "hey": "Hey! What can I do for you?",
    "how are you": "I'm doing great, thank you for asking! How about you?",
    "what's up": "Not much, just here to help you! What's up with you?",
    "how are you doing": "I'm doing great, thanks for asking! How about you?",
    
    "goodbye": "Goodbye! Have a great day ahead.",
    "bye": "Bye! Looking forward to assisting you again.",
    "see you later": "See you later! Take care.",
    "take care": "Take care! I'm here whenever you need help.",
    "have a great day": "Have a great day! Let me know if you need anything else.",
    "catch you later": "Catch you later! Feel free to return for assistance.",
    "I'm leaving now": "Alright! Have a good day!",
    "thank you": "You're welcome! Happy to help.",
    "thanks": "No problem! Let me know if you need anything else.",
    "I appreciate it": "Glad I could assist you.",
    "many thanks": "You're most welcome!",
    "I'm grateful": "It's my pleasure to help.",
    "thanks a ton": "You're welcome! Always here to assist.",
    "thank you so much": "You're very welcome! Happy to help.",
    "can you help me?": "Of course! Please tell me how I can assist you.",
    "I need assistance": "Sure! What do you need help with?",
    "can you assist me?": "I'm here to help! What can I do for you?",
    "I have a question": "Feel free to ask your question. I'm here for you.",
    "can you guide me?": "Absolutely! Tell me what you need guidance with.",
    "I need help with my account": "Sure! Let me know the issue you're facing with your account.",
    "how do I get started?": "I can help you get started! What would you like to know?",
    "how are you?": "I'm just a bot, but I'm here to make your day better!",
    "what's your name?": "My name is ShopBot! Let me help you with your shopping needs.",
    "what can you do?": "I can assist you with shopping queries, product info, order tracking, and more!",
    "tell me a joke": "Why did the shopper bring a ladder? To reach new heights of savings!",
    "make me laugh": "Why don't skeletons fight? They don't have the guts!",
    "are you human?": "Nope, I'm a chatbot here to help you 24/7.",
    "what are your skills?": "I can assist with shopping queries, product suggestions, and order support!",
    "can you tell me something interesting?": "Did you know online shopping is over 40 years old? It began in 1979!",
    "show me the latest products": "Here are our latest arrivals! [link or description]",
    "what are your bestsellers?": "Our bestsellers are listed here. Let me show you! [link or description]",
    "do you have discounts?": "Yes, we have discounts available! Check out these deals: [link].",
    "what are your current offers?": "Here are our current offers: [link].",
    "is there a sale going on?": "Yes, we have an ongoing sale! Check it out here: [link].",
    "what's trending right now?": "Here's what's trending: [Product 1, Product 2, Product 3].",
    "can you suggest some products?": "Sure! Let me suggest some great options for you.",
    "show me products under $50": "Here are some products under $50: [link or description].",
    "how can I track my order?": "You can track your order using the tracking number sent to your email.",
    "can I return a product?": "Yes, you can return products within 30 days. Check our return policy here: [link].",
    "what is your return policy?": "Our return policy allows returns within 30 days. More details here: [link].",
    "where is my order?": "You can track your order with the tracking details sent to your email.",
    "I want to check my order status": "You can check your order status on your account dashboard.",
    "can I get a refund?": "Refunds are processed within 7 business days after the return is approved.",
    "how can I cancel my order?": "You can cancel your order from your account dashboard or contact support.",
    "do you ship internationally?": "Yes, we ship internationally. Charges depend on your location.",
    "what are your shipping charges?": "Shipping charges vary based on your order and location. Check details at checkout.",
    "can I change my shipping address?": "Yes, you can change your shipping address from your account before dispatch.",
    "is express shipping available?": "Express shipping is available for select locations. Check options at checkout.",
    "how do I reschedule delivery?": "You can reschedule delivery by contacting support or using the delivery app link.",
    "how long does delivery take?": "Delivery times depend on your location. Typically, orders arrive in 3-7 days.",
    "how can I contact customer service?": "You can contact our customer service via chat, email, or phone.",
    "do you have a customer care number?": "Yes, our customer care number is available on our contact page.",
    "can I get live chat support?": "Yes, live chat support is available from 9 AM to 9 PM.",
    "is your support available 24/7?": "Our support is available 24/7 via email and chat.",
    "do you have gift cards?": "Yes, we offer gift cards! You can purchase them here: [link].",
    "what payment methods do you accept?": "We accept credit cards, PayPal, and cash on delivery.",
    "can I pay using cash on delivery?": "Yes, cash on delivery is available for select locations.",
    "is EMI available?": "Yes, EMI options are available for select products. Check details at checkout.",
    "how do I redeem a gift card?": "You can redeem a gift card at checkout by entering the code.",
    "can I use multiple payment methods?": "Currently, we allow one payment method per transaction.",
    "is online payment secure?": "Yes, our online payments are secure with encrypted transactions.",
    "do you have a loyalty program?": "Yes, join our loyalty program to earn points and get exclusive rewards!",
    "how can I redeem my reward points?": "You can redeem your reward points during checkout for discounts.",
    "is my personal information safe?": "Your personal information is protected by industry-standard encryption.",
    "how do I sign up for the loyalty program?": "Sign up for our loyalty program on our rewards page.",
    "can I pre-order a product?": "Yes, pre-orders are open for select products. Check the product page for details.",
    "do you offer installation services?": "We offer installation services for certain products. Contact support for assistance.",
    "how do I subscribe to your newsletter?": "Subscribe to our newsletter to stay updated on new arrivals and offers!",
    "do you have eco-friendly products?": "Yes, we have eco-friendly options. Check our eco-friendly category!",
    "what's your company mission?": "Our mission is to provide quality products with excellent customer service.",
    "where are your stores located?": "Our stores are located in multiple cities. Check our store locator for details."
}
